function o = triplepoint(im)

    o = im;
se(:,:,1) = [   0  1 0   ;...
                0  1 0   ;...
                0 0 0   ];
            
se(:,:,2) = [   0 0  1   ;...
                0  1 0   ;...
                0 0 0   ];
            
se(:,:,3) = [   0 0 0   ;...
                0  1  1   ;...
                0 0 0   ];
            
se(:,:,4) = [   0 0 0   ;...
                0  1 0   ;...
                0 0  1   ];
            
se(:,:,5) = [   0 0 0   ;...
                0  1 0   ;...
                0  1 0   ];
            
se(:,:,6) = [   0 0 0   ;...
                0  1 0   ;...
                 1 0 0   ];
            
se(:,:,7) = [   0 0 0   ;...
                 1  1 0   ;...
                0 0 0   ];
            
se(:,:,8) = [    1 0 0   ;...
                0  1 0   ;...
                0 0 0   ];

o = zeros(size(im));
for i=1:8
        o = o | hitormiss(im, se(:,:,i));
end

if 0
    Sa = [NaN 1 NaN; NaN 1 NaN; 1 NaN 1];
    Sb = [1 NaN NaN; NaN 1 NaN; 1 NaN 1];

    o = zeros(size(im));
    for i=1:4
        o = o | hitormiss(im, Sa);
        o = o | hitormiss(im, Sb);
        Sa = rot90(Sa);
        Sb = rot90(Sb);
    end
end
